export default actionTypes = {

    SIGNIN_PROG: "SIGNIN_PROG",
    SIGNIN_SUCC: "SIGNIN_SUCC",
    SIGNIN_FAIL: "SIGNIN_FAIL",

    SIGNUP_PROG: "SIGNUP_PROG",
    SIGNUP_SUCC: "SIGNUP_SUCC",
    SIGNUP_FAIL: "SIGNUP_FAIL",

    SIGN_OUT: "SIGN_OUT",

    SET_UNMOUNT_FLAG: "SET_UNMOUNT_FLAG",

    GET_TOKEN_AND_USER: "GET_TOKEN_AND_USER",

    CLEAR_ERROR: "CLEAR_ERROR",


    GET_BUS_ROUTE_PROG: "GET_BUS_ROUTE_PROG",
    GET_BUS_ROUTE_SUCC: "GET_BUS_ROUTE_SUCC",
    GET_BUS_ROUTE_FAIL: "GET_BUS_ROUTE_FAIL",

    CLEAR_ROUTE: "CLEAR_ROUTE",

    GET_BUS_INFO_PROG: "GET_BUS_INFO_PROG",
    GET_BUS_INFO_SUCC: "GET_BUS_INFO_SUCC",
    GET_BUS_INFO_FAIL: "GET_BUS_INFO_FAIL",

    CLEAR_INFO: "CLEAR_INFO",

    LIVE_TRACK_INFO_PROG: "LIVE_TRACK_INFO_PROG",
    LIVE_TRACK_INFO_SUCC: "LIVE_TRACK_INFO_SUCC",
    LIVE_TRACK_INFO_FAIL: "LIVE_TRACK_INFO_FAIL",

    SET_STOP_LOCATION_PROG: "SET_STOP_LOCATION_PROG",
    SET_STOP_LOCATION_SUCC: "SET_STOP_LOCATION_SUCC",
    SET_STOP_LOCATION_FAIL: "SET_STOP_LOCATION_FAIL",

    GET_ALL_BUS_INFO_PROG: "GET_ALL_BUS_INFO_PROG",
    GET_ALL_BUS_INFO_SUCC: "GET_ALL_BUS_INFO_SUCC",
    GET_ALL_BUS_INFO_FAIL: "GET_ALL_BUS_INFO_FAIL",

    UPDATE_BUS_NAME_PROG: "UPDATE_BUS_NAME_PROG",
    UPDATE_BUS_NAME_SUCC: "UPDATE_BUS_NAME_SUCC",
    UPDATE_BUS_NAME_FAIL: "UPDATE_BUS_NAME_FAIL",

    CALL_SUCCESS_FLAG_FALSE: "CALL_SUCCESS_FLAG_FALSE",

    GET_TIME_AND_DISTANCE_PROG: "GET_TIME_AND_DISTANCE_PROG",
    TIME_AND_DISTANCE_SUCC: "TIME_AND_DISTANCE_SUCC",
    GET_TIME_AND_DISTANCE_FAIL: "GET_TIME_AND_DISTANCE_FAIL"




}