export default actionTypes = {

    SIGNIN_PROG: "SIGNIN_PROG",
    SIGNIN_SUCC: "SIGNIN_SUCC",
    SIGNIN_FAIL: "SIGNIN_FAIL",

    SIGNUP_PROG: "SIGNUP_PROG",
    SIGNUP_SUCC: "SIGNUP_SUCC",
    SIGNUP_FAIL: "SIGNUP_FAIL",

    SIGN_OUT: "SIGN_OUT",

    SET_UNMOUNT_FLAG:"SET_UNMOUNT_FLAG",

    GET_TOKEN_AND_USER: "GET_TOKEN_AND_USER",

    CLEAR_ERROR: "CLEAR_ERROR",


    



}